// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW1RNP1i9PVwzKkcd4kxLDtX6x32LFhRc',
    appId: '1:519145971888:web:87bddf86ec08f060c3db75',
    messagingSenderId: '519145971888',
    projectId: 'cheers-f9c26',
    authDomain: 'cheers-f9c26.firebaseapp.com',
    storageBucket: 'cheers-f9c26.firebasestorage.app',
    measurementId: 'G-VVL5XHNCJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXl5-jhhioR5yOywO2hhaYCa_v4n9g7I',
    appId: '1:519145971888:android:529a961c465b2007c3db75',
    messagingSenderId: '519145971888',
    projectId: 'cheers-f9c26',
    storageBucket: 'cheers-f9c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtVp_36R4yFkujLvEK1DlwXbKz1cGSiw',
    appId: '1:519145971888:ios:f93d766f2a161129c3db75',
    messagingSenderId: '519145971888',
    projectId: 'cheers-f9c26',
    storageBucket: 'cheers-f9c26.firebasestorage.app',
    iosClientId: '519145971888-sjhcig884jabsp3qcprm26q053oakkj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheersFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVtVp_36R4yFkujLvEK1DlwXbKz1cGSiw',
    appId: '1:519145971888:ios:f93d766f2a161129c3db75',
    messagingSenderId: '519145971888',
    projectId: 'cheers-f9c26',
    storageBucket: 'cheers-f9c26.firebasestorage.app',
    iosClientId: '519145971888-sjhcig884jabsp3qcprm26q053oakkj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cheersFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW1RNP1i9PVwzKkcd4kxLDtX6x32LFhRc',
    appId: '1:519145971888:web:b7f44518b4a9e8dfc3db75',
    messagingSenderId: '519145971888',
    projectId: 'cheers-f9c26',
    authDomain: 'cheers-f9c26.firebaseapp.com',
    storageBucket: 'cheers-f9c26.firebasestorage.app',
    measurementId: 'G-HTXGWZ0NB5',
  );

}